apiVersion: apps/v1
kind: Deployment
metadata:
  name: gayathriala-deploy
  labels:
    app: gayathriala-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gayathriala-app
  template:
    metadata:
      labels:
        app: gayathriala-app
    spec:
      containers:
      - name: gayathriala-container
        image: gayathriala/gayathriala:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gayathriala-np-service
  labels:
    app: gayathriala-app
spec:
  selector:
    app: gayathriala-app

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
